"""adding user

Revision ID: faa892034cff
Revises: 
Create Date: 2022-10-11 13:15:02.901805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa892034cff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('chore', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chore', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chore', type_='foreignkey')
    op.drop_column('chore', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
